# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: avatar.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'avatar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61vatar.proto\x12\x06\x61vatar\"<\n\rAvatarRequest\x12\x14\n\x0csource_image\x18\x01 \x01(\x0c\x12\x15\n\rdriving_audio\x18\x02 \x01(\x0c\"&\n\x0e\x41vatarResponse\x12\x14\n\x0cvideo_output\x18\x01 \x01(\x0c\x32Q\n\rAvatarService\x12@\n\rAnimateAvatar\x12\x15.avatar.AvatarRequest\x1a\x16.avatar.AvatarResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'avatar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVATARREQUEST']._serialized_start=24
  _globals['_AVATARREQUEST']._serialized_end=84
  _globals['_AVATARRESPONSE']._serialized_start=86
  _globals['_AVATARRESPONSE']._serialized_end=124
  _globals['_AVATARSERVICE']._serialized_start=126
  _globals['_AVATARSERVICE']._serialized_end=207
# @@protoc_insertion_point(module_scope)
